### ISSUE TITLE
Can you compile it?

### ISSUE THREAD

**Issue by ashi876** [AtaLuZiK/npp-plugins-x64#1]
Be deeply grateful

**Comment by ashi876** [comment]
I need a binary version

**Comment by AtaLuZiK** [comment]
Sure, you can compile with cmake or download compiled here [NppLightExplorer.dll (x64)](http://assets.kiljaeden.net/npp-plugins/x64/NppLightExplorer.dll)

**Comment by ashi876** [comment]
very good!
you are A good big man
too thanks
